### ISSUE TITLE
Error writing to flash w/ Black Magic Probe

### ISSUE THREAD

**Issue by pinsonn** [dhylands/1BITSY#1]
Successfully compiled micropython for 1Bitsy (in Knoppix -- all repos pulled today 2/15/18). While trying to flash `.elf` to 1Bitsy w/ BMP, I get the following error:

```
(gdb) load
Ignoring packet error, continuing. . . 
Loading section .isr_vector, size 0x3a6c lma 0x8000000
Error writing data to flash
```

**Comment by dhylands** [comment]
I have to admit that I've never tried flashing the elf using gdb. I've only done it using the builtin DFU bootloader (i.e. using the instructions found in the README.md file of this repository).

If you're going to use gdb, then you should follow the 1Bitsy quickstart guide and make sure you can flash those images.
https://1bitsy.org/overview/quickstart/

I also have some other code in this repository that I have flashed to the 1Bitsy using gdb, and that repo includes a gdbinit file. You can find that repo here: https://github.com/dhylands/stm32-test

In that repo you can do `make BOARD=1BITSY run` and it should launch gdb to run blinky.elf.

I just moved recently and can't seem to find my 1Bitsy right now.

**Comment by pinsonn** [comment]
Yes . . . flashing 1bitsy code or my own code (STM32Cube HAL) w/ BMP/GDB works fine. DFU load appears to complete -- I get a write of 14956 bytes to 0x08000000, and a write of 282220 bytes to 0x08020000, followed by "Exiting DFU". No device shows up at `/dev/ttyACM*` and no storage device shows up, however. If I hold down the button on `PC1` while plugging in the 1bitsy, I get a "1 flash, 2 flash, 3 flash" pattern from the LED, then nothing (no tty, no storage device). If I do not hold down the button, I get nothing at all (no flashes, no tty, no storage device).

I'm happy to dig further . . .  it would be great to get micropython working on 1bitsy.

**Comment by dhylands** [comment]
It's also possible that something has changed with the system clock initialization of whatnot. It looks like I created the board definition on Nov 25, 2016.

So you could try checking out a version of MicroPython from that time frame.

The 415 and the 405 are pretty similar, so I'm surprised that there are issues, but lots has changed and sometimes there are changes needed in the board definitions to keep up.

It would also be good to look at the history of changes to the board definition files for the PYBV11 image during that timeframe, since similar changes may need to be made to the 1BITSY files.

**Comment by pinsonn** [comment]
Good suggestion -- I should have looked through commit history for micropython. Issue was not w/ system clocks -- that all looked fine. Changes were related to USB initialization:

- remove/comment out #define USE_USB_FS in hal header file
- Enable USB and USB FS in board config (add MICROPY_HW_ENABLE_ USB (1) and MICROPY_HW_USB_FS (1)

I was able to get firmware onto 1BITSY w/ DFU (pydfu.py has a habit of timing out, but eventually got it to work). Original issue w/ flashing `.elf` using BMP remains, unfortunately. I'm not really sure how to proceed in debugging that.

**Comment by dhylands** [comment]
I took your PR and built micropython. I was then able to flash it using gdb without any troubles. Here's my log:
```
2023 >arm-none-eabi-gdb build-1BITSY/firmware.elf 
GNU gdb (7.10-1ubuntu3+9) 7.10
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "--host=x86_64-linux-gnu --target=arm-none-eabi".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from build-1BITSY/firmware.elf...done.
(gdb) target extended-remote /dev/ttyACM0
Remote debugging using /dev/ttyACM0
(gdb) monitor version
Black Magic Probe (Firmware v1.6-rc0-210-gf131460) (Hardware Version 2)
Copyright (C) 2015  Black Sphere Technologies Ltd.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

(gdb) monitor jtag_scan
Target voltage: 3.3V
Available Targets:
No. Att Driver
 1      STM32F4xx
(gdb) attach 1
Attaching to program: /home/dhylands/Dropbox/micropython/micropython/ports/stm32/build-1BITSY/firmware.elf, Remote target
0x08000a5e in sync_fs ()
(gdb) load
Loading section .isr_vector, size 0x39ac lma 0x8000000
Loading section .text, size 0x49048 lma 0x8020000
Loading section .data, size 0x20 lma 0x8069048
Start address 0x804b2f0, load size 313876
Transfer rate: 18 KB/sec, 971 bytes/write.
(gdb) run
The program being debugged has been started already.
Start it from the beginning? (y or n) y
Starting program: /home/dhylands/Dropbox/micropython/micropython/ports/stm32/build-1BITSY/firmware.elf 
```

**Comment by pinsonn** [comment]
Closed -- able to get micropython on 1bitsy w/ changes in merged PR. Sorry for the delay in closing.
